#!/bin/bash

today=$(date +"%Y-%m-%d")
tomorrow=$(date -d "tomorrow" +"%Y-%m-%d")
yesterday=$(date -d "yesterday" +"%Y-%m-%d")
file="$ZETTELKASTEN/daily-notes/$today.md"

cd "$ZETTELKASTEN" || exit

new_note() {
  touch "$file"

  # Format the file with the daily template
  cat <<EOF >"$file"
# $today

[[$yesterday]] - [[$tomorrow]]

## Journal


## Notes

EOF

}

# Default values
OPEN_FILE=true

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
  --no-open)
    OPEN_FILE=false
    shift
    ;;
  -*)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
done

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
  echo "File does not exist, creating new daily note."
  new_note --no-open
fi

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
if $OPEN_FILE; then
  nvim '+ normal Gzzo' "$file" -c :NoNeckPain
fi
