#!/bin/bash
# Gentime generates the time in HH:MM format
# Can be called with arguments h and number to generate a markdown heading
# For example: 'gentime h 3' will generate '### 14:16'

header=""
time=$(date +"%H:%M")

if [[ $# -gt 0 ]]; then

  # handling wrong arguments
  if [[ $# -eq 1 || "$1" != "h" ]]; then
    echo "Usage: gentime h 2 to generate with markdown heading ##"
    exit 1
  fi

  # format markdown heading if arguments h, n are given
  if [[ $# -eq 2 ]]; then
    for i in $(seq 1 $2); do
      header+="#"
    done
    header+=" "$time
    echo "$header"
    exit 1
  fi
fi

# if no arguments given, generate the time
echo "$time"
