#!/bin/bash

# Function to prompt the user for a filename
get_filename() {
  read -p "Enter a filename: " filename
  echo "$filename"
}

# Function to create a file in the specified directory
create_file() {
  local dir="$1"
  local filename="$2"
  local filepath="$dir/$filename.md"

  # Change into the directory
  cd "$dir" || exit 1

  # Create the file
  touch "$filepath"

  # Format the file
  {
    echo "# "
    echo -en "\n"
  } >>"$filepath"

  echo "$filepath" # Output the file path for external use
}

# Default values
OPEN_FILE=true
TARGET_DIR="$ZETTELKASTEN/05-inbox"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
  --no-open)
    OPEN_FILE=false
    shift
    ;;
  -*)
    echo "Unknown option: $1"
    exit 1
    ;;
  *)
    filename="$1"
    shift
    ;;
  esac
done

# Prompt the user if no filename is provided
if [[ -z "$filename" ]]; then
  filename=$(get_filename)
fi

# Validate filename
if [[ -z "$filename" ]]; then
  echo "Filename cannot be empty."
  exit 1
fi

# Create the file
filepath=$(create_file "$TARGET_DIR" "$filename")

# Open the file in Neovim unless --no-open was specified
if $OPEN_FILE; then
  nvim '+ normal ggzz' -c "startinsert!" "$filepath" -c :NoNeckPain
fi
