#!/bin/bash

# Script to install common tools and applications

# Diagnostics
sudo apt install -y btop

# python
# pyenv dependencies
sudo apt update
sudo apt install build-essential libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev curl git \
  libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

# sudo apt install python3-venv pip  ~# might not need this?
curl https://pyenv.run | bash
pyenv install 3.11.11 # required for nginx-language-server
pyenv global 3.11.11

# Blog
brew install hugo

# Kubernetes tools
brew install kubectl kubectx derailed/k9s/k9s helm fluxcd/tap/flux siderolabs/tap/talosctl cilium-cli
curl -sSfL \
  https://github.com/EnterpriseDB/kubectl-cnp/raw/main/install.sh |
  sudo sh -s -- -b /usr/local/bin
curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
